```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r echo = FALSE, message = FALSE}
library(tidyverse)
options(scipen = 999)

arthritis <- read_csv("https://raw.githubusercontent.com/cosmos-uci-dshs/data/main/RheumArth_Tx_AgeComparisons.csv") %>% 
  janitor::clean_names() %>% 
  mutate(sex = case_when(sex == 0 ~ "female",
                   sex == 1 ~ "male")) %>% 
  mutate(sex = as.factor(sex)) %>% 
  mutate(age_gp = case_when(age_gp == 1 ~ "control",
                   age_gp == 2 ~ "elderly")) %>% 
  mutate(age_gp = as.factor(age_gp)) %>% 
  mutate(cdai_yn = case_when(cdai_yn == 1 ~ "no",
                             cdai_yn == 2 ~ "yes")) %>%
  mutate(cdai_yn = as.factor(cdai_yn))
```

```{r}
glimpse(arthritis)
```

```{r}
arthritis %>% 
  mutate(age_months = age*12)
```

```{r}
arthritis %>%
  mutate(cdai_level = case_when(
    cdai <=2.8 ~ "Remission", 
    cdai > 2.8 & cdai <= 10 ~ "Low",
    cdai > 10 & cdai <=22  ~ "Moderate",
    cdai > 22 ~ "High"))
```
```{r}
arthritis %>% 
  mutate(cdai_level = case_when(
    cdai <=2.8 ~ "Remission", 
    cdai > 2.8 & cdai <= 10 ~ "Low",
    cdai > 10 & cdai <=22  ~ "Moderate",
    cdai > 22 ~ "High")) %>% 
  ggplot(aes(x = cdai_level)) +
  geom_bar()
```

